--TABLE USUARIO
SET IDENTITY_INSERT Usuario ON
INSERT INTO [Usuario] ([id_usuario], [nome_usuario], [sobrenome_usuario], [email_usuario], [senha_usuario], [telefone_usuario], [url_imageUsuario])VALUES(1,'Gabriel', 'Braga', 'gabriel@gmail.com',  CONVERT(VARCHAR(32), HashBytes('MD5', 'senha'), 2), '19912341234', 'https://media.licdn.com/dms/image/D4D03AQF8_49jhGHaPQ/profile-displayphoto-shrink_200_200/0/1672679645770?e=1698883200&v=beta&t=_z8lHA9dRihZWPEu1WiNaxcR-Ys2faM0ISIZ_Lv-SAs')
INSERT INTO [Usuario] ([id_usuario], [nome_usuario], [sobrenome_usuario], [email_usuario], [senha_usuario], [telefone_usuario], [url_imageUsuario])VALUES(2,'Herica', 'Cadoni', 'herica@gmail.com',  CONVERT(VARCHAR(32), HashBytes('MD5', 'dotnet'), 2), '19900000000', 'https://media.licdn.com/dms/image/D4D03AQHMEVhimbcBvw/profile-displayphoto-shrink_200_200/0/1684157299956?e=1698883200&v=beta&t=5rgUQrZIux9C0gFQ-oFMJNMIGgEcr0izRbbQ1cr6hZ4')
INSERT INTO [Usuario] ([id_usuario], [nome_usuario], [sobrenome_usuario], [email_usuario], [senha_usuario], [telefone_usuario])VALUES(3,'Diego', 'Negretto', 'diego@gmail.com', CONVERT(VARCHAR(32), HashBytes('MD5', 'professor'), 2), '19911111111')
INSERT INTO [Usuario] ([id_usuario], [nome_usuario], [sobrenome_usuario], [email_usuario], [senha_usuario], [telefone_usuario])VALUES(4,'Victor', 'Seila', 'victor@gmail.com', CONVERT(VARCHAR(32), HashBytes('MD5', 'seila'), 2), '19922222222')
INSERT INTO [Usuario] ([id_usuario], [nome_usuario], [sobrenome_usuario], [email_usuario], [senha_usuario], [telefone_usuario])VALUES(5,'Aurora', 'Boreal', 'aurora@gmail.com', CONVERT(VARCHAR(32), HashBytes('MD5', 'boreal'), 2), '19933333333')
INSERT INTO [Usuario] ([id_usuario], [nome_usuario], [sobrenome_usuario], [email_usuario], [senha_usuario], [telefone_usuario])VALUES(6,'Helliot', 'Haha', 'helliot@gmail.com', CONVERT(VARCHAR(32), HashBytes('MD5', 'helloworld'), 2), '19944444444')
SET IDENTITY_INSERT [Usuario] OFF
